### ISSUE TITLE
Compare chart broken on Firefox v95.0

### ISSUE THREAD

**Issue by stothe2** [brain-score/brain-score.web#120]
I'm using Firefox v95.0 on MacOS 11.0.1, with no ad blocker. Let me know if there's any other details you'd like to debug this.

<img width="1540" alt="Screen Shot 2021-12-13 at 4 09 15 PM" src="https://user-images.githubusercontent.com/4976443/145889160-20556539-7955-4205-81e0-82fc76489634.png">

**Comment by stothe2** [comment]
I looked into it a little more:
- When you first load brain-score.org, the plot shows up broken for me on Firefox, Safari and Chrome
- Staying in the same window, if you click, say, brain-score.org/#about, the plot gets fixed up.
- Now, if I go back to brain-score.org, the plot _remains_ fixed (but **not** in "incognito" mode)

**Comment by mschrimpf** [comment]
I initially thought this was because we're accessing in javascript that aren't yet loaded, but the `compare.js` script is correctly inside a `$(document).ready` https://github.com/brain-score/brain-score.web/blob/master/static/benchmarks/js/compare.js#L1

**Comment by mschrimpf** [comment]
this seems to be working on firefox now, please reopen if that is not the case.
