### ISSUE TITLE
missing engineering benchmarks for submitted model?

### ISSUE THREAD

**Issue by jenellefeather** [brain-score/brain-score.web#153]
I submitted a model on brainscore and need to rerun some of the behavioral and engineering benchmarks, but it looks like I cannot choose to run the engineering benchmarks from the list on the website. Is this to be expected, or should they be in the list?

![image](https://user-images.githubusercontent.com/16601844/197628104-6b6052a7-74e2-411e-9670-5fc2866ae462.png)

**Comment by asbudhkar** [comment]
Hi
Any idea when this will be resolved? I need to run the engineering benchmarks but not getting scores.

**Comment by mschrimpf** [comment]
this should be resolved -- all new model submissions are automatically run on the engineering benchmarks again.
If you encounter this error again, please reopen this issue.
