### ISSUE TITLE
Improve website loading times

### ISSUE THREAD

**Issue by kvfairchild** [brain-score/brain-score.web#222]
Website pages (especially model pages, e.g. https://www.brain-score.org/model/vision/1885) are very slow to load.

**Comment by mschrimpf** [comment]
not sure we're ready to close this -- model pages are still incredibly slow. Is there another issue specifically for the model pages @deirdre-k?

**Comment by deirdre-k** [comment]
Good point! I had been lumping that into #221 in my mind but it makes sense to keep separate. I'll make another issue to track model pages specifically so that we can differentiate it from site-wide issues.
