### ISSUE TITLE
submission zip template not found

### ISSUE THREAD

**Issue by KogniJannis** [brain-score/brain-score.web#225]
Hi everyone,
congrats on the new web-design!
I tried to complete the deep-dive tutorials and did not find the zip-file when it says "You can download the sample zip file here." in step 2 on https://www.brain-score.org/tutorial/deepdive_1
Is this supposed to be clickable or am I mistaken?

Is the zip-file accessible elsewhere or is it simply not possible to upload right now due to the ongoing development of v2.0?
Best, Jannis

**Comment by mschrimpf** [comment]
might be related to https://github.com/brain-score/brain-score.web/pull/224; @mike-ferguson can you help?

**Comment by KogniJannis** [comment]
thanks a lot! I found the zip file at the branch that updates the tutorial.
Seems to be working.
(I dont quite understand the tensorflow wrapper though, gonna ask over at brainscore_vision)
