### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by kvfairchild** [brain-score/brain-score.web#232]
Currently the FAQ link at the bottom of Brain-Score points to the [Read the Docs](https://brain-score.readthedocs.io/en/latest/index.html). It would be good to instead have an actual FAQ.

- [x]  Add path in URLs.py
- [x]  Add user.py method
- [x]  Create HTML page for FAQ
- [x]  Style HTML Page
- [ ]  Add actual material for FAQ @pellegreene
- [x]  Point "new issues" to a community page

**Comment by pellegreene** [comment]
Goal is to have this live on the website on 2/26. Target date is to have these questions outlined by EOD 2/16, so the appropriate people can have a change to respond in the following week.
