### ISSUE TITLE
Create sponsors page

### ISSUE THREAD

**Issue by kvfairchild** [brain-score/brain-score.web#238]
Add logos for top-level sponsor organizations

**Comment by kvfairchild** [comment]
Mockup:
![‎‎sponsors_mock ‎001 png ‎001](https://github.com/brain-score/brain-score.web/assets/14812599/49236c3a-4f3b-47dc-93c9-787698a87e12)

**Comment by mike-ferguson** [comment]
Addressed in PR #243
