### ISSUE TITLE
Tutorials Not Found (not linking to correct pages)

### ISSUE THREAD

**Issue by MKentKraus** [brain-score/brain-score.web#350]
Hi! I would like to benchmark some models in the vision leaderboard.

However, the [FAQ](https://www.brain-score.org/faq/) and the [leaderboard](https://www.brain-score.org/vision/) link to pages that do not exist:
https://www.brain-score.org/tutorial/quickstart
https://www.brain-score.org/tutorial/deepdive_1

When they should link to:
https://www.brain-score.org/tutorials/models/quickstart
https://www.brain-score.org/tutorials/models/deepdive_1

**Comment by MKentKraus** [comment]
Hi! The tutorials were helpful for uploading CVT models, thanks for making them. 

I have a question about the resulting Brain Score, and how it shifts over time. When I was working on another project two years ago, the Brain Score average for VGG-19 and VGG-16 models was 0.402 and 0.404 respectively. Now it is significantly lower, at  .183 and .184. Do you think that the drop in score is a result of new tests being added? Thanks!

**Comment by KartikP** [comment]
Hi @MKentKraus, that is exactly correct. As new benchmarks/tests are added, they will be scored on most/all models. As this will affect the average score, their ranking will also change.
