### ISSUE TITLE
emails not arriving

### ISSUE THREAD

**Issue by mschrimpf** [brain-score/brain-score.web#54]
multiple users have reported that they are not receiving emails

**Comment by mschrimpf** [comment]
@jjpr-mit do you know if the credentials for jenkins.dicarlo@gmail.com changed?
```
MessagingException message: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 203sm12488967qkd.81 - gsmtp
```
http://braintree.mit.edu:8080/job/run_benchmarks/738/console

**Comment by jjpr-mit** [comment]
Odd.  I didn't do anything with it.  

> @jjpr-mit do you know if the credentials for [jenkins.dicarlo@gmail.com](mailto:jenkins.dicarlo@gmail.com) changed?
> 
> ```
> MessagingException message: 535-5.7.8 Username and Password not accepted. Learn more at
> 535 5.7.8  https://support.google.com/mail/?p=BadCredentials 203sm12488967qkd.81 - gsmtp
> ```
> 
> http://braintree.mit.edu:8080/job/run_benchmarks/738/console

**Comment by mschrimpf** [comment]
Just logged in manually which worked but the last sent email was on 11/20/20.
I tried to turn on less secure apps but it wants to verify activity through •••• •••••89, maybe @franzigeiger still has access to this?

**Comment by mschrimpf** [comment]
ok access for less secure apps is enabled and the recovery info is updated. Hopefully it'll work now

**Comment by mschrimpf** [comment]
an email was sent at noon, this seems to work again
