### ISSUE TITLE
Error 403 Forbidden when running engineering benchmarks

### ISSUE THREAD

**Issue by yugrao** [brain-score/brain-score.web#71]
When an engineering benchmark is selected in the model resubmission section, a Forbidden 403 Page comes up.
![image](https://user-images.githubusercontent.com/10038643/122837925-fb81ac80-d2c2-11eb-8789-276641754dec.png)
![image](https://user-images.githubusercontent.com/10038643/122837936-02102400-d2c3-11eb-83d6-a2fb19170c67.png)

**Comment by mschrimpf** [comment]
this should be resolved, but please reopen this issue if you encounter this again.
