### ISSUE TITLE
"Server Error (500)" when attempting to create an account or change password

### ISSUE THREAD

**Issue by efirdc** [brain-score/brain-score.web#96]
Hello,

I am encountering a "Server Error (500)" when attempting to create an account or reset a password for an existing account on http://www.brain-score.org/. I think creating the account was partly successful because when I try again it says it already exists. However, I didn't receive a confirmation email.

Thanks in advance,
Cory

**Comment by mike-ferguson** [comment]
Hi Cory, Thanks for adding this issue - it is a bug and we are working right now to fix it. It should be only about a week, and I will update within about a week with. Thanks!

**Comment by mike-ferguson** [comment]
Cory - this issue should be solved now. Thanks again!
